#
# mdn-bcd-collector: app.yaml
# Google App Engine configuration for the collector
#
# © Google LLC, Gooborg Studios
# See the LICENSE file for copyright details
#

runtime: nodejs16
env_variables:
  GCLOUD_STORAGE_BUCKET: fiji-mdn-collector
