import chalk from 'chalk';
import esMain from 'es-main';
import fs from 'fs-extra';
import inquirer from 'inquirer';
import NodeGit from 'nodegit';

import {exec} from './scripts.js';

const gitRepo = await NodeGit.Repository.open('.');

const currentVersion = (
  await fs.readJson(new URL('./package.json', import.meta.url))
).version;

const prepare = async () => {
  console.log(chalk`{blue Fetching...}`);
  await gitRepo.fetchAll();

  console.log(chalk`{blue Checking status...}`);
  const status = await gitRepo.getStatus();
  if (status.length) {
    console.error(
      chalk`{red You currently have {bold uncommitted changes}. Please {bold commit} or {bold stash} your changes and try again.}`
    );
    return false;
  }

  console.log(chalk`{blue Checking for GitHub CLI...}`);
  try {
    exec('gh --version');
  } catch (e) {
    console.error(
      chalk`{red This script depends on the {bold GitHub CLI}. Please {bold install} the CLI using the following instructions:} {blue https://cli.github.com/}`
    );
    return false;
  }

  console.log(chalk`{blue Checking out main branch...}`);
  try {
    await gitRepo.checkoutBranch('main');
    await gitRepo.mergeBranches('main', 'origin/main');
  } catch (e) {
    const commit = await gitRepo.getBranchCommit('refs/remotes/origin/main');
    const branch = await gitRepo.createBranch('main', commit);
    NodeGit.Branch.setUpstream(branch, 'refs/remotes/origin/main');
  }

  return true;
};

const getNewVersion = async () => {
  const versionParts = currentVersion.split('.').map((x) => Number(x));
  const newVersions = [
    `${versionParts[0] + 1}.0.0`,
    `${versionParts[0]}.${versionParts[1] + 1}.0`,
    `${versionParts[0]}.${versionParts[1]}.${versionParts[2] + 1}`
  ];

  const answers = await inquirer.prompt([
    {
      type: 'list',
      name: 'newVersion',
      message: 'How should we bump the version?',
      choices: [
        {
          name: chalk`Major {blue (${newVersions[0]})}`,
          value: newVersions[0]
        },
        {
          name: chalk`Minor {blue (${newVersions[1]})}`,
          value: newVersions[1]
        },
        {
          name: chalk`Patch {blue (${newVersions[2]})}`,
          value: newVersions[2]
        },
        {
          name: chalk`{yellow Cancel}`,
          value: 'cancel'
        }
      ],
      default: 2
    }
  ]);

  return answers.newVersion;
};

const doVersionBump = async (newVersion) => {
  for (const f of ['./package.json', './package-lock.json']) {
    const filepath = new URL(f, import.meta.url);
    const data = await fs.readJson(filepath);
    data.version = newVersion;
    await fs.writeJson(filepath, data, {spaces: 2});
  }
};

const getChanges = () => {
  const changes = exec(
    `git log --pretty=reference v${currentVersion}..origin/main`
  )
    .toString('utf8')
    .split('\n')
    .map((c) => '- ' + c.substring(8))
    .filter((c) => !!c);
  return changes.join('\n');
};

const doChangelogUpdate = async () => {
  const filepath = new URL('./CHANGELOG.md', import.meta.url);
  const changelog = await fs.readFile(filepath, 'utf8');
  const idx = changelog.indexOf('##');
  const newChangelog =
    changelog.substring(0, idx) +
    getChanges() +
    '\n\n' +
    changelog.substring(idx, changelog.length);
  await fs.writeFile(filepath, newChangelog, 'utf8');
};

const prepareBranch = async (newVersion) => {
  const branchName = `release-${newVersion}`;

  const authorSignature = await NodeGit.Signature.default();
  const commit = await gitRepo.getHeadCommit();

  const branch = await gitRepo.createBranch(branchName, commit);
  await gitRepo.checkoutBranch(branch);

  exec('git stage package.json package-lock.json CHANGELOG.md');
  exec(
    `git commit -m "Release ${newVersion}" -m "" -m "Release v${newVersion}, generated by \\\`release.js\\\`."`
  );

  return branchName;
};

const main = async () => {
  if (!(await prepare())) {
    process.exit(1);
  }

  const newVersion = await getNewVersion();
  if (newVersion == 'cancel') {
    console.log(chalk`{yellow Release cancelled by user}`);
    process.exit(0);
  }

  console.log('');

  await doVersionBump(newVersion);
  await doChangelogUpdate();

  const branch = await prepareBranch(newVersion);

  const answers = await inquirer.prompt([
    {
      type: 'confirm',
      name: 'confirm',
      message: `Ready to release ${newVersion}?`
    }
  ]);

  if (answers.confirm) {
    exec(`gh pr create -f -B ${branch}`);
  } else {
    console.log(chalk`{yellow Release cancelled by user}`);
  }

  exec('git checkout main');
  exec(`git branch -d ${branch}`);
};

/* istanbul ignore if */
if (esMain(import.meta)) {
  await main();
}
