[Exposed=Window]
interface AccessibleNode : EventTarget {
  // members omitted until this is actually shipped
};

partial interface Element {
  readonly attribute DOMString? computedRole;
  readonly attribute DOMString? computedName;
  readonly attribute AccessibleNode? accessibleNode;
};
