// https://wicg.github.io/budget-api/#budget-service-interface

[Exposed=(Window,Worker)]
interface BudgetService {
  Promise<double> getCost(OperationType operation);
  Promise<sequence<BudgetState>> getBudget();

  Promise<boolean> reserve(OperationType operation);
};

[Exposed=(Window,Worker)]
interface BudgetState {
  readonly attribute double budgetAt;
  readonly attribute DOMTimeStamp time;
};
