// https://github.com/w3c/clipboard-apis/issues/25

partial interface Document {
  attribute EventHandler onbeforecopy;
  attribute EventHandler onbeforecut;
  attribute EventHandler onbeforepaste;
};

partial interface Element {
  attribute EventHandler onbeforecopy;
  attribute EventHandler onbeforecut;
  attribute EventHandler onbeforepaste;
};
