
partial namespace console {
  undefined exception(any msg);
  undefined profile(optional DOMString profileName);
  undefined profileEnd(optional DOMString profileName);
  undefined timeStamp(DOMString label);
};
