// TODO: why do we have this?

[SecureContext]
interface mixin CredentialUserData {
  readonly attribute USVString name;
  readonly attribute USVString iconURL;
};

Credential includes CredentialUserData;
