// TODO: why do we have this?

[SecureContext]
interface mixin CredentialUserData {
  readonly attribute USVString name;
  readonly attribute USVString iconURL;
};

Credential includes CredentialUserData;

partial interface PasswordCredential {
  attribute FormData additionalData;
  attribute USVString idName;
  attribute USVString passwordName;
};
