partial interface AnimationEvent {
  undefined initAnimationEvent(DOMString type, boolean bubbles, boolean cancelable, DOMString animationName, float elapsedTime);
};

partial interface CSSKeyframesRule {
  // https://github.com/WebKit/WebKit/blob/2ebcb2f801bc60264b1a154a7970e2581a438db2/Source/WebCore/css/CSSKeyframesRule.idl#L35
  undefined insertRule(CSSOMString rule);
};

partial interface TransitionEvent {
  readonly attribute DOMString animationName;
  undefined initTransitionEvent();
};

// http://w3.org/TR/2009/WD-css3-2d-transforms-20090320/#point-interface
[Exposed=Window]
interface Point {
  attribute float x;
  attribute float y;
};

// https://github.com/WebKit/WebKit/blob/9940f5c6cd901c3cce4efb372ebd94d808218d80/Source/WebCore/dom/WebKitAnimationEvent.idl
[Exposed=Window]
interface WebKitAnimationEvent : Event {
  constructor(DOMString type);

  readonly attribute DOMString animationName;
  readonly attribute double elapsedTime;
  readonly attribute DOMString pseudoElement;

  // https://developer.apple.com/documentation/webkitjs/webkitanimationevent/1807040-initwebkitanimationevent
  // https://trac.webkit.org/changeset/103751/webkit
  undefined initWebKitAnimationEvent();
};
