dictionary ElementRegistrationOptions {
  object? prototype = null;
  DOMString? extends = null;
};

partial interface Document {
  any registerElement(DOMString type, optional ElementRegistrationOptions options = {});
};

partial interface Element {
  readonly attribute boolean tabStop;
};
