// https://www.w3.org/TR/2012/WD-file-writer-api-20120417/

[Exposed=Window,Worker]
interface BlobBuilder {
  constructor();
  Blob getBlob (optional DOMString contentType);
  void append (DOMString text, optional DOMString endings);
  void append (Blob data);
  void append (ArrayBuffer data);
};

[Exposed=Window,Worker]
interface FileSaver : EventTarget {
  constructor(Blob data);
  void abort ();
  const unsigned short INIT = 0;
  const unsigned short WRITING = 1;
  const unsigned short DONE = 2;
  readonly attribute unsigned short readyState;
  readonly attribute DOMError error;
  attribute EventHandler onwritestart;
  attribute EventHandler onprogress;
  attribute EventHandler onwrite;
  attribute EventHandler onabort;
  attribute EventHandler onerror;
  attribute EventHandler onwriteend;
};

[Exposed=Window,Worker]
interface FileSaverSync {
  // empty in spec
};

[Exposed=Window,Worker]
interface FileWriter : FileSaver {
  readonly attribute unsigned long long position;
  readonly attribute unsigned long long length;
  void write (Blob data);
  void seek (long long offset);
  void truncate (unsigned long long size);
};

[Exposed=Window,Worker]
interface FileWriterSync {
  readonly attribute unsigned long long position;
  readonly attribute unsigned long long length;
  void write (Blob data);
  void seek (long long offset);
  void truncate (unsigned long long size);
};
