// https://blog.foolip.org/2014/07/21/history-of-the-fullscreen-api/

partial interface HTMLVideoElement {
  readonly attribute boolean webkitSupportsFullscreen;
  readonly attribute boolean webkitDisplayingFullscreen;
  undefined webkitEnterFullscreen();
  undefined webkitExitFullscreen();
  undefined webkitEnterFullScreen();
  undefined webkitExitFullScreen();
};

partial interface Element {
  const unsigned short ALLOW_KEYBOARD_INPUT = 1;
  undefined webkitRequestFullScreen(unsigned short flags);
};

partial interface Document {
  readonly attribute boolean webkitIsFullScreen;
  readonly attribute boolean webkitFullScreenKeyboardInputAllowed;
  readonly attribute Element? webkitCurrentFullScreenElement;
  undefined webkitCancelFullScreen();
};

partial interface Element {
  undefined mozRequestFullScreen();
};

partial interface Document {
  readonly attribute boolean mozFullScreen;
  readonly attribute boolean mozFullScreenEnabled;
  readonly attribute Element? mozFullScreenElement;
  undefined mozCancelFullScreen();
};

partial interface Element {
  undefined webkitRequestFullscreen();
};

partial interface Document {
  readonly attribute boolean webkitFullscreenEnabled;
  readonly attribute Element? webkitFullscreenElement;
  undefined webkitExitFullscreen();
};

partial interface Element {
  undefined msRequestFullscreen();
};

partial interface Document {
  readonly attribute boolean msFullscreenEnabled;
  readonly attribute Element? msFullscreenElement;
  undefined msExitFullscreen();
};

// Event handler attributes, added widely to find them wherever they are.
partial interface Element {
  attribute EventHandler onmozfullscreenchange;
  attribute EventHandler onmozfullscreenerror;
  attribute EventHandler onmsfullscreenchange;
  attribute EventHandler onmsfullscreenerror;
  attribute EventHandler onwebkitfullscreenchange;
  attribute EventHandler onwebkitfullscreenerror;
};
partial interface mixin GlobalEventHandlers {
  attribute EventHandler onmozfullscreenchange;
  attribute EventHandler onmozfullscreenerror;
  attribute EventHandler onmsfullscreenchange;
  attribute EventHandler onmsfullscreenerror;
  attribute EventHandler onwebkitfullscreenchange;
  attribute EventHandler onwebkitfullscreenerror;
};

// Capitalization variant of window.fullscreen supported by Firefox:
partial interface Window {
  readonly attribute boolean fullScreen;
};
