// https://blog.foolip.org/2014/07/21/history-of-the-fullscreen-api/

partial interface Document {
  readonly attribute boolean webkitIsFullScreen;
  readonly attribute boolean webkitFullScreenKeyboardInputAllowed;
  readonly attribute Element? webkitCurrentFullScreenElement;
  undefined webkitCancelFullScreen();
};

partial interface Document {
  readonly attribute boolean mozFullScreen;
  readonly attribute boolean mozFullScreenEnabled;
  undefined mozCancelFullScreen();
};

partial interface Document {
  readonly attribute boolean webkitFullscreenEnabled;
  readonly attribute Element? webkitFullscreenElement;
  undefined webkitExitFullscreen();
};

// Capitalization variant of window.fullscreen supported by Firefox:
partial interface Window {
  readonly attribute boolean fullScreen;
};
