
[Exposed=Window]
interface GamepadAxisEvent : GamepadEvent {
  constructor(DOMString type, optional GamepadAxisEventInit eventInitDict = {});
  readonly attribute unsigned long axis;
  readonly attribute double value;
};

[Exposed=Window]
interface GamepadButtonEvent : GamepadEvent {
    constructor(DOMString type, optional GamepadButtonEventInit eventInitDict = {});
    readonly attribute unsigned long button;
    readonly attribute double value;
};
