partial interface DOMMatrixReadOnly {
  undefined scaleNonUniformSelf(optional unrestricted double scaleX = 1, optional unrestricted double scaleY = 1);
  undefined transform();
};

partial interface Window {
  attribute object WebKitCSSMatrix;
};
