partial interface DOMMatrixReadOnly {
  void scaleNonUniformSelf(optional unrestricted double scaleX = 1, optional unrestricted double scaleY = 1);
  void transform();
};

partial interface Window {
  attribute object WebKitCSSMatrix;
};
