// https://developer.apple.com/documentation/webkitjs/gestureevent

[Exposed=Window]
interface GestureEvent : UIEvent {
  constructor();
  undefined initGestureEvent();

  readonly attribute boolean altKey;
  readonly attribute boolean ctrlKey;
  readonly attribute boolean metaKey;
  readonly attribute float rotation;
  readonly attribute float scale;
  readonly attribute boolean shiftKey;
  readonly attribute EventTarget? target;

  readonly attribute long clientX;
  readonly attribute long clientY;
  readonly attribute long screenX;
  readonly attribute long screenY;
};

// https://developer.mozilla.org/en-US/docs/Web/API/MSGestureEvent

typedef object MSGesture;

[Exposed=Window]
interface MSGestureEvent : UIEvent {
  constructor();
  undefined initGestureEvent();

  readonly attribute double expansion;
  readonly attribute MSGesture gestureObject;
  readonly attribute double rotation;
  readonly attribute double scale;
  readonly attribute double translationX;
  readonly attribute double translationY;
  readonly attribute double velocityAngular;
  readonly attribute double velocityExpansion;
  readonly attribute double velocityX;
  readonly attribute double velocityY;
};
