// https://developer.apple.com/documentation/webkitjs/gestureevent

interface GestureEvent {
  constructor(DOMString type, boolean canBubble, boolean cancelable, Window? view, long detail, long screenX, long screenY, long clientX, long clientY, boolean ctrlKey, boolean altKey, boolean shiftKey, boolean metaKey, EventTarget? target, float scale, float rotation);
  undefined initGestureEvent(DOMString type, boolean canBubble, boolean cancelable, Window? view, long detail, long screenX, long screenY, long clientX, long clientY, boolean ctrlKey, boolean altKey, boolean shiftKey, boolean metaKey, EventTarget? target, float scale, float rotation);
  readonly attribute float rotation;
  readonly attribute float scale;
};
