[Exposed=(Window,Worker)] interface IDBDatabaseException {};
[Exposed=(Window,Worker)] interface IDBEnvironment {};

partial interface IDBIndex {
  readonly attribute boolean isAutoLocale;
  readonly attribute DOMString locale;
};

[Exposed=(Window,Worker)] interface IDBLocaleAwareKeyRange {};

partial interface IDBVersionChangeEvent {
  readonly attribute unsigned long long? version;
};

// https://bugs.chromium.org/p/chromium/issues/detail?id=711586

enum IDBDataLossAmount {
  "none",
  "total"
};

partial interface IDBVersionChangeEvent {
  readonly attribute IDBDataLossAmount dataLoss;
  readonly attribute DOMString dataLossMessage;
};

partial interface Window {
  readonly attribute IDBFactory webkitIndexedDB;
};
