// These entries are in Chromium and BCD, but they're not described in the
// Manifest Incubations (https://wicg.github.io/manifest-incubations/) spec:
// https://github.com/WICG/manifest-incubations/issues/36
// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/app_banner/before_install_prompt_event.idl;l=10-11;drc=253e72e77ded2b7199dc1ec0b8401e2fbd08faa8

dictionary AppBannerPromptResult {
  required DOMString platform;
  required AppBannerPromptOutcome outcome;
};

partial interface BeforeInstallPromptEvent {
  readonly attribute FrozenArray<DOMString> platforms;
  readonly attribute Promise<AppBannerPromptResult> userChoice;
};
