partial interface MediaStream {
  readonly attribute boolean ended;
  readonly attribute DOMString label;
  attribute EventHandler onactive;
  attribute EventHandler oninactive;
  undefined stop();
};

interface MediaStreamEvent : Event {
  constructor();
  readonly attribute MediaStream stream;
};

partial interface MediaStreamTrack {
  any getSources();
  attribute EventHandler onoverconstrained;
  readonly attribute boolean _readonly;
  readonly attribute boolean remote;
};

partial interface MediaStreamTrackAudioSourceNode {
  readonly attribute any mediaStreamTrack;
};
