// https://bugzilla.mozilla.org/show_bug.cgi?id=1689222
partial interface MediaSource {
  attribute EventHandler onsourceclosed;
};

partial interface SourceBufferList {
  SourceBufferList item(unsigned long index);
};
