// https://bugzilla.mozilla.org/show_bug.cgi?id=1689222
partial interface MediaSource {
  attribute EventHandler onsourceclosed;
};

partial interface SourceBuffer {
  Promise<undefined> appendBufferAsync();
  undefined appendStream();
  undefined removeAsync();
  attribute any trackDefaults;
};

partial interface SourceBufferList {
  SourceBufferList item(unsigned long index);
};

[Exposed=Window]
interface TrackDefault {
  constructor();

  readonly attribute DOMString byteStreamTrackID;
  readonly attribute any kinds;
  readonly attribute any label;
  readonly attribute any language;
  readonly attribute any type;
};

[Exposed=Window]
interface TrackDefaultList {
  constructor();
  readonly attribute long length;
};
