partial interface Node {
  readonly attribute object baseURIObject;
  boolean hasAttributes();
  attribute object nodePrincipal;
  readonly attribute Node rootNode;
};

partial interface ProcessingInstruction {
  readonly attribute any data;
};
