// https://github.com/whatwg/notifications/commit/11f25cccb909adc7e8b5569f8e5e20c482234860
// https://github.com/mozilla/gecko-dev/blob/06dbf167c94b89fb06f74a2d1b1c5d3ccabceb92/dom/webidl/Notification.webidl#L27
// https://bugzilla.mozilla.org/show_bug.cgi?id=1689565
partial interface Notification {
  static Promise<sequence<Notification>> get(optional GetNotificationOptions filter = {});
};
