partial interface PaymentAddress {
  readonly attribute DOMString languageCode;
  readonly attribute DOMString regionCode;
};

partial interface PaymentRequest {
  // https://github.com/w3c/payment-request/pull/931
  [NewObject] Promise<boolean> hasEnrolledInstrument();

  readonly attribute PaymentAddress? paymentAddress;
  readonly attribute DOMString requestId;
};

// https://github.com/w3c/payment-request/pull/929
[SecureContext, Exposed=Window]
interface MerchantValidationEvent : Event {
  constructor(DOMString type, optional MerchantValidationEventInit eventInitDict = {});
  readonly attribute DOMString methodName;
  readonly attribute USVString validationURL;
  undefined complete(Promise<any> merchantSessionPromise);
};

dictionary MerchantValidationEventInit : EventInit {
  DOMString methodName = "";
  USVString validationURL = "";
};

partial interface PaymentRequest {
  attribute EventHandler onmerchantvalidation;
};

partial interface HTMLIFrameElement {
  attribute boolean allowPaymentRequest;
};
