// https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/payments/abort_payment_event.idl;drc=c2e7d4f0b24814b0d1c51a964db34ec5b4930756
// https://github.com/w3c/payment-handler/pull/170
// https://github.com/w3c/payment-handler/pull/207
[Exposed=ServiceWorker]
interface AbortPaymentEvent : ExtendableEvent {
  constructor(DOMString type, optional ExtendableEventInit eventInitDict = {});
  undefined respondWith(Promise<boolean> paymentAbortedResponse);
};
partial interface ServiceWorkerGlobalScope {
  attribute EventHandler onabortpayment;
};

partial interface CanMakePaymentEvent {
  readonly attribute FrozenArray<PaymentDetailsModifier> modifiers;
};
