// https://www.w3.org/TR/2015/WD-proximity-20150903/

dictionary DeviceProximityEventInit : EventInit {
  double value;
  double min;
  double max;
};

[Exposed=Window]
interface DeviceProximityEvent : Event {
  constructor(DOMString type, optional DeviceProximityEventInit eventInitDict = {});
  readonly attribute double value;
  readonly attribute double min;
  readonly attribute double max;
};

partial interface Window {
  attribute EventHandler ondeviceproximity;
  attribute EventHandler onuserproximity;
};
