partial interface PushManager {
  Promise<boolean> hasPermission();
  Promise<any> register();
  Promise<sequence<any>> registrations();
  Promise<any> unregister();
};

partial interface PushSubscription {
  readonly attribute DOMString subscriptionId;
};
