partial interface RTCCertificate {
  any getSupportedAlgorithms();
};

partial interface RTCDataChannel {
  readonly attribute short stream;
};

interface RTCIdentityErrorEvent : Event {
  readonly attribute DOMString idp;
  readonly attribute DOMString loginUrl;
  readonly attribute DOMString protocol;
};

interface RTCIdentityEvent : Event {
  readonly attribute DOMString assertion;
};

partial interface RTCPeerConnection {
  readonly attribute any defaultIceServers;
  any getDefaultIceServers();
  MediaStream getStreamById(DOMString id);
  attribute EventHandler onidentityresult;
  attribute EventHandler onidpassertionerror;
  attribute EventHandler onidpvalidationerror;
  attribute EventHandler onpeeridentity;
};

partial interface RTCPeerConnectionIceErrorEvent {
  readonly attribute any hostCandidate;
};

partial interface RTCRtpReceiver {
  readonly attribute RTCDtlsTransport rtcpTransport;
};

partial interface RTCRtpSender {
  readonly attribute RTCDtlsTransport rtcpTransport;
};

partial interface RTCRtpTransceiver {
  readonly attribute boolean stopped;
};
