partial interface Screen {
  readonly attribute long left;
  readonly attribute long top;
  attribute EventHandler onorientationchange;
  undefined lockOrientation();
  undefined unlockOrientation();

  attribute double mozBrightness;
  attribute boolean mozEnabled;
};
