partial interface Element {
  // event handler attribute in the wrong place
  attribute EventHandler onselectstart;
};

partial interface Selection {
  readonly attribute Node? baseNode;
  readonly attribute unsigned long baseOffset;
  readonly attribute Node? extentNode;
  readonly attribute unsigned long extentOffset;

  undefined modify(optional DOMString alter = "",
              optional DOMString direction = "",
              optional DOMString granularity = "");
};
