partial interface FetchEvent {
  readonly attribute boolean isReload;
};

// https://github.com/w3c/ServiceWorker/pull/1207
[Exposed=ServiceWorker]
interface InstallEvent : ExtendableEvent {
  constructor(DOMString type, optional object init);

  // https://bugs.chromium.org/p/chromium/issues/detail?id=470032
  // https://github.com/w3c/ServiceWorker/issues/661
  readonly attribute ServiceWorker? activeWorker;
};

partial interface ServiceWorkerContainer {
  attribute EventHandler onerror;
};
