// https://w3c.github.io/setImmediate/

interface mixin WindowTimersExtension {
  long setImmediate(any handler, any... args);
  undefined clearImmediate(long handle);
};
Window includes WindowTimersExtension;
