partial interface Element {
  // https://trac.webkit.org/changeset/136092/webkit
  ShadowRoot createShadowRoot();
  ShadowRoot webkitCreateShadowRoot();

  NodeList getDestinationInsertionPoints();
  readonly attribute boolean openOrClosedShadowRoot;
};

partial interface Event {
  readonly attribute object path;
};

partial interface Text {
  NodeList getDestinationInsertionPoints();
};
