partial interface SourceBuffer {
  Promise<undefined> appendBufferAsync();
  undefined appendStream();
  undefined changeType();
  undefined removeAsync();
  attribute any trackDefaults;
};

interface TrackDefault {
  constructor();

  readonly attribute DOMString byteStreamTrackID;
  readonly attribute any kinds;
  readonly attribute any label;
  readonly attribute any language;
  readonly attribute any type;
};

interface TrackDefaultList {
  constructor();
  readonly attribute long length;
};
