[Exposed=Window]
interface webkitSpeechGrammar {
  constructor();
};

[Exposed=Window]
interface webkitSpeechGrammarList {
  constructor();
};

[Exposed=Window]
interface webkitSpeechRecognition : EventTarget {
  constructor();
};

[Exposed=Window]
interface webkitSpeechRecognitionError : Event {
  constructor(DOMString type);
};

[Exposed=Window]
interface webkitSpeechRecognitionEvent : Event {
  constructor(DOMString type);
};
