partial interface SpeechGrammar {
  constructor();
};

partial interface SpeechGrammarList {
  // https://github.com/WICG/speech-api/issues/26
  undefined addFromUri(DOMString src, optional float weight = 1.0);
};

partial interface SpeechRecognition {
  attribute any serviceURI;
};

partial interface SpeechRecognitionEvent {
  readonly attribute USVString emma;
  readonly attribute DOMString interpretation;
};

[Exposed=Window]
interface webkitSpeechGrammar {
  constructor();
};

[Exposed=Window]
interface webkitSpeechGrammarList {
  constructor();
};

[Exposed=Window]
interface webkitSpeechRecognition : EventTarget {
  constructor();
};

[Exposed=Window]
interface webkitSpeechRecognitionError : Event {
  constructor(DOMString type);
};

[Exposed=Window]
interface webkitSpeechRecognitionEvent : Event {
  constructor(DOMString type);
};
