// https://www.w3.org/TR/2012/WD-quota-api-20120703/#storageusagecallback-callback
callback StorageUsageCallback = undefined (unsigned long long currentUsageInBytes, unsigned long long currentQuotaInBytes);

// https://www.w3.org/TR/2012/WD-quota-api-20120703/#storagequotacallback-callback
callback StorageQuotaCallback = undefined (unsigned long long grantedQuotaInBytes);

// https://www.w3.org/TR/2012/WD-quota-api-20120703/#storageerrorcallback-callback
callback StorageErrorCallback = undefined (DOMError error);

// https://www.w3.org/TR/2012/WD-quota-api-20120703/#storagequota-interface
[Exposed=Window]
interface StorageQuota {
  undefined queryUsageAndQuota(StorageUsageCallback successCallback, optional StorageErrorCallback errorCallback);
  undefined requestQuota(unsigned long long newQuotaInBytes, optional StorageQuotaCallback successCallback, optional StorageErrorCallback errorCallback);
};
