partial interface SVGElement {
  readonly attribute long offsetHeight;
  readonly attribute long offsetLeft;
  readonly attribute long offsetParent;
  readonly attribute long offsetTop;
  readonly attribute long offsetWidth;
};

partial interface SVGImageElement {
  undefined decode();
  readonly attribute boolean decoding;
};

[Exposed=Window]
interface SVGPoint {
  undefined matrixTransform();
  attribute long x;
  attribute long y;
};

[Exposed=Window] interface SVGMeshElement : SVGGeometryElement {};
[Exposed=Window] interface SVGSolidcolorElement : SVGElement {};
[Exposed=Window] interface SVGUnknownElement {};

// SVGZoomAndPan has been both an interface and a mixin in implementations.
// Cover all bases:
[Exposed=Window]
interface SVGZoomAndPan {
  const unsigned short SVG_ZOOMANDPAN_UNKNOWN = 0;
  const unsigned short SVG_ZOOMANDPAN_DISABLE = 1;
  const unsigned short SVG_ZOOMANDPAN_MAGNIFY = 2;
};
interface mixin ZoomAndPan {
  const unsigned short SVG_ZOOMANDPAN_UNKNOWN = 0;
  const unsigned short SVG_ZOOMANDPAN_DISABLE = 1;
  const unsigned short SVG_ZOOMANDPAN_MAGNIFY = 2;
  attribute unsigned short zoomAndPan;
};
SVGSVGElement includes ZoomAndPan;
SVGViewElement includes ZoomAndPan;

typedef object SVGPathSegClosePath;
typedef object SVGPathSegMovetoAbs;
typedef object SVGPathSegMovetoRel;
typedef object SVGPathSegLinetoAbs;
typedef object SVGPathSegLinetoRel;
typedef object SVGPathSegCurvetoCubicAbs;
typedef object SVGPathSegCurvetoCubicRel;
typedef object SVGPathSegCurvetoQuadraticAbs;
typedef object SVGPathSegCurvetoQuadraticRel;
typedef object SVGPathSegArcAbs;
typedef object SVGPathSegArcRel;
typedef object SVGPathSegLinetoHorizontalAbs;
typedef object SVGPathSegLinetoHorizontalRel;
typedef object SVGPathSegLinetoVerticalAbs;
typedef object SVGPathSegLinetoVerticalRel;
typedef object SVGPathSegCurvetoCubicSmoothAbs;
typedef object SVGPathSegCurvetoCubicSmoothRel;
typedef object SVGPathSegCurvetoQuadraticSmoothAbs;
typedef object SVGPathSegCurvetoQuadraticSmoothRel;

// https://www.w3.org/TR/SVG11/text.html#InterfaceSVGAltGlyphDefElement
[Exposed=Window]
interface SVGAltGlyphDefElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/text.html#InterfaceSVGAltGlyphItemElement
[Exposed=Window]
interface SVGAltGlyphItemElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/animate.html#InterfaceSVGAnimateColorElement
[Exposed=Window]
interface SVGAnimateColorElement : SVGAnimationElement {
};

// https://www.w3.org/TR/SVG11/color.html#InterfaceSVGColorProfileElement
[Exposed=Window]
interface SVGColorProfileElement : SVGElement {
  attribute DOMString local;
  attribute DOMString name;
  attribute unsigned short renderingIntent;
};

// https://www.w3.org/TR/SVG11/types.html#InterfaceSVGExternalResourcesRequired
[Exposed=Window]
interface SVGExternalResourcesRequired {
  readonly attribute SVGAnimatedBoolean externalResourcesRequired;
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGFontFaceElement
[Exposed=Window]
interface SVGFontFaceElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGFontFaceFormatElement
[Exposed=Window]
interface SVGFontFaceFormatElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGFontFaceNameElement
[Exposed=Window]
interface SVGFontFaceNameElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGFontFaceSrcElement
[Exposed=Window]
interface SVGFontFaceSrcElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGFontFaceUriElement
[Exposed=Window]
interface SVGFontFaceUriElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGGlyphElement
[Exposed=Window]
interface SVGGlyphElement : SVGElement {
};

partial interface SVGGraphicsElement {
  // https://github.com/mdn/browser-compat-data/issues/8745
  attribute boolean autofocus;
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGHKernElement
[Exposed=Window]
interface SVGHKernElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/coords.html#InterfaceSVGMatrix
[Exposed=Window]
interface SVGMatrix {
  attribute float a;
  attribute float b;
  attribute float c;
  attribute float d;
  attribute float e;
  attribute float f;

  SVGMatrix multiply(SVGMatrix secondMatrix);
  SVGMatrix inverse();
  SVGMatrix translate(float x, float y);
  SVGMatrix scale(float scaleFactor);
  SVGMatrix scaleNonUniform(float scaleFactorX, float scaleFactorY);
  SVGMatrix rotate(float angle);
  SVGMatrix rotateFromVector(float x, float y);
  SVGMatrix flipX();
  SVGMatrix flipY();
  SVGMatrix skewX(float angle);
  SVGMatrix skewY(float angle);
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGMissingGlyphElement
[Exposed=Window]
interface SVGMissingGlyphElement : SVGElement {
};

// https://www.w3.org/TR/SVG11/paths.html#InterfaceSVGPathElement
partial interface SVGPathElement {
  unsigned long getPathSegAtLength(float distance);
  SVGPathSegClosePath createSVGPathSegClosePath();
  SVGPathSegMovetoAbs createSVGPathSegMovetoAbs(float x, float y);
  SVGPathSegMovetoRel createSVGPathSegMovetoRel(float x, float y);
  SVGPathSegLinetoAbs createSVGPathSegLinetoAbs(float x, float y);
  SVGPathSegLinetoRel createSVGPathSegLinetoRel(float x, float y);
  SVGPathSegCurvetoCubicAbs createSVGPathSegCurvetoCubicAbs(float x, float y, float x1, float y1, float x2, float y2);
  SVGPathSegCurvetoCubicRel createSVGPathSegCurvetoCubicRel(float x, float y, float x1, float y1, float x2, float y2);
  SVGPathSegCurvetoQuadraticAbs createSVGPathSegCurvetoQuadraticAbs(float x, float y, float x1, float y1);
  SVGPathSegCurvetoQuadraticRel createSVGPathSegCurvetoQuadraticRel(float x, float y, float x1, float y1);
  SVGPathSegArcAbs createSVGPathSegArcAbs(float x, float y, float r1, float r2, float angle, boolean largeArcFlag, boolean sweepFlag);
  SVGPathSegArcRel createSVGPathSegArcRel(float x, float y, float r1, float r2, float angle, boolean largeArcFlag, boolean sweepFlag);
  SVGPathSegLinetoHorizontalAbs createSVGPathSegLinetoHorizontalAbs(float x);
  SVGPathSegLinetoHorizontalRel createSVGPathSegLinetoHorizontalRel(float x);
  SVGPathSegLinetoVerticalAbs createSVGPathSegLinetoVerticalAbs(float y);
  SVGPathSegLinetoVerticalRel createSVGPathSegLinetoVerticalRel(float y);
  SVGPathSegCurvetoCubicSmoothAbs createSVGPathSegCurvetoCubicSmoothAbs(float x, float y, float x2, float y2);
  SVGPathSegCurvetoCubicSmoothRel createSVGPathSegCurvetoCubicSmoothRel(float x, float y, float x2, float y2);
  SVGPathSegCurvetoQuadraticSmoothAbs createSVGPathSegCurvetoQuadraticSmoothAbs(float x, float y);
  SVGPathSegCurvetoQuadraticSmoothRel createSVGPathSegCurvetoQuadraticSmoothRel(float x, float y);
};

// https://www.w3.org/TR/SVG11/types.html#InterfaceSVGRect
[Exposed=Window]
interface SVGRect {
  attribute float x;
  attribute float y;
  attribute float width;
  attribute float height;
};

// https://www.w3.org/TR/SVG11/types.html#InterfaceSVGRenderingIntent
[Exposed=Window]
interface SVGRenderingIntent {
  // Rendering Intent Types
  const unsigned short RENDERING_INTENT_UNKNOWN = 0;
  const unsigned short RENDERING_INTENT_AUTO = 1;
  const unsigned short RENDERING_INTENT_PERCEPTUAL = 2;
  const unsigned short RENDERING_INTENT_RELATIVE_COLORIMETRIC = 3;
  const unsigned short RENDERING_INTENT_SATURATION = 4;
  const unsigned short RENDERING_INTENT_ABSOLUTE_COLORIMETRIC = 5;
};

partial interface SVGSVGElement {
  // https://www.w3.org/TR/SVG11/struct.html#InterfaceSVGSVGElement
  attribute DOMString contentScriptType;
  attribute DOMString contentStyleType;
  readonly attribute SVGRect viewport;
  readonly attribute float pixelUnitToMillimeterX;
  readonly attribute float pixelUnitToMillimeterY;
  readonly attribute float screenPixelToMillimeterX;
  readonly attribute float screenPixelToMillimeterY;
};

// https://www.w3.org/TR/SVG11/text.html#InterfaceSVGTRefElement
[Exposed=Window]
interface SVGTRefElement : SVGTextPositioningElement {
};

// https://www.w3.org/TR/SVG11/fonts.html#InterfaceSVGVKernElement
[Exposed=Window]
interface SVGVKernElement : SVGElement {
};

partial interface SVGViewElement {
  // https://www.w3.org/TR/SVG11/linking.html#InterfaceSVGViewElement
  readonly attribute SVGStringList viewTarget;
};
