partial interface CompositionEvent {
  attribute DOMString locale;
};

// https://developer.apple.com/documentation/webkitjs/gestureevent

[Exposed=Window]
interface GestureEvent : UIEvent {
  constructor();
  undefined initGestureEvent();

  readonly attribute boolean altKey;
  readonly attribute boolean ctrlKey;
  readonly attribute boolean metaKey;
  readonly attribute float rotation;
  readonly attribute float scale;
  readonly attribute boolean shiftKey;
  readonly attribute EventTarget? target;

  readonly attribute long clientX;
  readonly attribute long clientY;
  readonly attribute long screenX;
  readonly attribute long screenY;
};

// https://developer.mozilla.org/en-US/docs/Web/API/MSGestureEvent

typedef object MSGesture;

[Exposed=Window]
interface MSGestureEvent : UIEvent {
  constructor();
  undefined initGestureEvent();

  readonly attribute double expansion;
  readonly attribute MSGesture gestureObject;
  readonly attribute double rotation;
  readonly attribute double scale;
  readonly attribute double translationX;
  readonly attribute double translationY;
  readonly attribute double velocityAngular;
  readonly attribute double velocityExpansion;
  readonly attribute double velocityX;
  readonly attribute double velocityY;
};

// https://www.w3.org/TR/1999/WD-DOM-Level-2-19990923/events.html#Events-KeyEvent
[Exposed=Window]
interface KeyEvent : UIEvent {
  readonly attribute boolean ctrlKey;
  readonly attribute boolean shiftKey;
  readonly attribute boolean altKey;
  readonly attribute boolean metaKey;
  readonly attribute unsigned long keyCode;
  readonly attribute unsigned long charCode;
  undefined initKeyEvent();
};

partial interface KeyboardEvent {
  // https://github.com/mozilla/gecko-dev/blob/b9384b091e901b3283ce24b6610e80699d79fd06/dom/webidl/KeyboardEvent.webidl#L75
  undefined initKeyEvent();

  // https://www.w3.org/TR/2003/WD-DOM-Level-3-Events-20030331/events.html#Events-KeyboardEvent
  readonly attribute boolean altGraphKey;

  // https://www.w3.org/TR/2009/WD-DOM-Level-3-Events-20090908/#events-Events-KeyboardEvent-keyIdentifier
  readonly attribute DOMString keyIdentifier;

  // https://www.w3.org/TR/2003/WD-DOM-Level-3-Events-20030331/events.html#Events-KeyboardEvent
  readonly attribute unsigned long keyLocation;

  // https://www.w3.org/TR/2014/WD-DOM-Level-3-Events-20140925/#widl-KeyboardEvent-which
  readonly attribute unsigned long which;
};

partial interface MouseEvent {
  // https://github.com/mozilla/gecko-dev/blob/06dbf167c94b89fb06f74a2d1b1c5d3ccabceb92/dom/webidl/MouseEvent.webidl#L101
  undefined initNSMouseEvent();

  // https://chromium.googlesource.com/chromium/src/+/6ad4130faeeead16d8bf620c4387283da143ac09/third_party/blink/renderer/core/events/mouse_event.idl#73
  // https://github.com/WebKit/WebKit/blob/226e0bffa2f0c87d04fb84a6c63472f9a2b8c122/Source/WebCore/dom/MouseEvent.idl#L59
  readonly attribute Node fromElement;
  readonly attribute Node toElement;

  // https://chromium.googlesource.com/chromium/src/+/6ad4130faeeead16d8bf620c4387283da143ac09/third_party/blink/renderer/core/events/mouse_event.idl#75
  readonly attribute long layerX;
  readonly attribute long layerY;

  // Also on UIEVent
  readonly attribute byte which;

  // https://github.com/mozilla/gecko-dev/blob/06dbf167c94b89fb06f74a2d1b1c5d3ccabceb92/dom/webidl/MouseEvent.webidl#L99
  readonly attribute unsigned short mozInputSource;

  // https://github.com/mozilla/gecko-dev/blob/06dbf167c94b89fb06f74a2d1b1c5d3ccabceb92/dom/webidl/MouseEvent.webidl#L89
  readonly attribute float mozPressure;

  // https://github.com/WebKit/WebKit/blob/226e0bffa2f0c87d04fb84a6c63472f9a2b8c122/Source/WebCore/dom/MouseEvent.idl#L45
  readonly attribute double webkitForce;
};

[Exposed=Window]
interface MouseScrollEvent : Event {
};

[Exposed=Window]
interface MouseWheelEvent : Event {
  readonly attribute long wheelDelta;
  readonly attribute long? wheelDeltaX;
  readonly attribute long? wheelDeltaY;
};

partial interface UIEvent {
  // https://github.com/mozilla/gecko-dev/blob/06dbf167c94b89fb06f74a2d1b1c5d3ccabceb92/dom/webidl/UIEvent.webidl#L32
  // https://github.com/WebKit/WebKit/blob/226e0bffa2f0c87d04fb84a6c63472f9a2b8c122/Source/WebCore/dom/UIEvent.idl#L30
  readonly attribute long layerX;
  readonly attribute long layerY;

  // https://github.com/WebKit/WebKit/blob/226e0bffa2f0c87d04fb84a6c63472f9a2b8c122/Source/WebCore/dom/UIEvent.idl#L32
  readonly attribute long pageX;
  readonly attribute long pageY;

  // https://github.com/mozilla/gecko-dev/blob/06dbf167c94b89fb06f74a2d1b1c5d3ccabceb92/dom/webidl/UIEvent.webidl#L36
  readonly attribute Node? rangeParent;
  readonly attribute long rangeOffset;

  // TODO: source?
  undefined cancelBubble();
  readonly attribute boolean isChar;
};

partial interface WheelEvent {
  // Was in Edge 12
  undefined initWheelEvent();

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1629934-initwebkitwheelevent
  // Note that the interface was never called WebKitWheelEvent, there was just
  // this initWebKitWheelEvent variant added here:
  // https://trac.webkit.org/changeset/55436/webkit
  undefined initWebKitWheelEvent();

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1630157-webkitdirectioninvertedfromdevic
  readonly attribute boolean webkitDirectionInvertedFromDevice;

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1633018-wheeldelta
  readonly attribute long wheelDelta;

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1633615-wheeldeltax
  readonly attribute long wheelDeltaX;

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1631213-wheeldeltay
  readonly attribute long wheelDeltaY;
};

[Exposed=Window]
interface WebKitMutationObserver {
  constructor(MutationCallback callback);
};
