partial interface CompositionEvent {
  attribute DOMString locale;
};

// https://developer.apple.com/documentation/webkitjs/gestureevent

[Exposed=Window]
interface GestureEvent : UIEvent {

  undefined initGestureEvent();

  readonly attribute boolean altKey;
  readonly attribute boolean ctrlKey;
  readonly attribute boolean metaKey;
  readonly attribute float rotation;
  readonly attribute float scale;
  readonly attribute boolean shiftKey;
  readonly attribute EventTarget? target;

  readonly attribute long clientX;
  readonly attribute long clientY;
  readonly attribute long screenX;
  readonly attribute long screenY;
};

partial interface KeyboardEvent {
  // https://www.w3.org/TR/2009/WD-DOM-Level-3-Events-20090908/#events-Events-KeyboardEvent-keyIdentifier
  readonly attribute DOMString keyIdentifier;
};

partial interface MouseEvent {
  // https://chromium.googlesource.com/chromium/src/+/6ad4130faeeead16d8bf620c4387283da143ac09/third_party/blink/renderer/core/events/mouse_event.idl#75
  readonly attribute long layerX;
  readonly attribute long layerY;
};

[Exposed=Window]
interface MouseScrollEvent : Event {
};

partial interface WheelEvent {
  // https://developer.apple.com/documentation/webkitjs/wheelevent/1633018-wheeldelta
  readonly attribute long wheelDelta;

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1633615-wheeldeltax
  readonly attribute long wheelDeltaX;

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1631213-wheeldeltay
  readonly attribute long wheelDeltaY;
};
