partial interface CompositionEvent {
  attribute DOMString locale;
  // https://w3c.github.io/uievents/#idl-interface-CompositionEvent-initializers
  undefined initCompositionEvent();
};

// https://www.w3.org/TR/1999/WD-DOM-Level-2-19990923/events.html#Events-KeyEvent
[Exposed=Window]
interface KeyEvent : UIEvent {
  readonly attribute boolean ctrlKey;
  readonly attribute boolean shiftKey;
  readonly attribute boolean altKey;
  readonly attribute boolean metaKey;
  readonly attribute unsigned long keyCode;
  readonly attribute unsigned long charCode;
  undefined initKeyEvent();
};

partial interface KeyboardEvent {
  // https://w3c.github.io/uievents/#idl-interface-KeyboardEvent-initializers
  undefined initKeyboardEvent();

  // https://github.com/mozilla/gecko-dev/blob/b9384b091e901b3283ce24b6610e80699d79fd06/dom/webidl/KeyboardEvent.webidl#L75
  undefined initKeyEvent();

  // https://www.w3.org/TR/2003/WD-DOM-Level-3-Events-20030331/events.html#Events-KeyboardEvent
  readonly attribute boolean altGraphKey;

  // https://www.w3.org/TR/2009/WD-DOM-Level-3-Events-20090908/#events-Events-KeyboardEvent-keyIdentifier
  readonly attribute DOMString keyIdentifier;

  // https://www.w3.org/TR/2003/WD-DOM-Level-3-Events-20030331/events.html#Events-KeyboardEvent
  readonly attribute unsigned long keyLocation;

  // https://www.w3.org/TR/2014/WD-DOM-Level-3-Events-20140925/#widl-KeyboardEvent-which
  readonly attribute unsigned long which;
};

partial interface MouseEvent {
  readonly attribute Node fromElement;
  readonly attribute Node toElement;
  readonly attribute long layerX;
  readonly attribute long layerY;
};

// https://w3c.github.io/uievents/#legacy-mutationevent-events
[Exposed=Window]
interface MutationEvent : Event {
  const unsigned short MODIFICATION = 1;
  const unsigned short ADDITION = 2;
  const unsigned short REMOVAL = 3;

  readonly attribute Node? relatedNode;
  readonly attribute DOMString prevValue;
  readonly attribute DOMString newValue;
  readonly attribute DOMString attrName;
  readonly attribute unsigned short attrChange;

  undefined initMutationEvent(DOMString type, boolean bubbles, boolean cancelable, Node? relatedNode, DOMString prevValue, DOMString newValue, DOMString attrName, unsigned short attrChange);
};

partial interface UIEvent {
  // https://w3c.github.io/uievents/#idl-interface-UIEvent-initializers
  undefined initUIEvent();

  undefined cancelBubble();
  readonly attribute boolean isChar;
  readonly attribute long layerX;
  readonly attribute long layerY;
  readonly attribute long pageX;
  readonly attribute long pageY;
};

partial interface WheelEvent {
  // https://w3c.github.io/uievents/#idl-interface-WheelEvent-initializers
  undefined initWheelEvent();

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1629934-initwebkitwheelevent
  undefined initWebKitWheelEvent();

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1630157-webkitdirectioninvertedfromdevic
  readonly attribute boolean webkitDirectionInvertedFromDevice;

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1633018-wheeldelta
  readonly attribute long wheelDelta;

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1633615-wheeldeltax
  readonly attribute long wheelDeltaX;

  // https://developer.apple.com/documentation/webkitjs/wheelevent/1631213-wheeldeltay
  readonly attribute long wheelDeltaY;
};

[Exposed=Window]
interface WebKitMutationObserver {
  constructor(MutationCallback callback);
};
