// https://rniwa.github.io/undo-api/
// https://whsieh.github.io/UndoManager/

[Exposed=Window]
interface UndoItem {
  constructor(UndoItemInit initDict);
  readonly attribute DOMString label;
  readonly attribute boolean merged;
};

callback UndoItemCallback = undefined ();

dictionary UndoItemInit {
  required DOMString label;
  boolean merged = false;
  UndoItemCallback undo = null;
  UndoItemCallback redo = null;
};

[Exposed=Window]
interface UndoManager {
  undefined undo();
  undefined redo();
  undefined clearUndo();
  undefined clearRedo();
  undefined addItem(UndoItem item);
  undefined removeItem(unsigned long index);
  UndoItem item(unsigned long index);
  readonly attribute unsigned long length;
  readonly attribute unsigned long position;
};

partial interface Element {
  readonly attribute UndoManager undoManager;
  [CEReactions] attribute boolean undoScope;
};

// https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/dom/DocumentUndoMananger.idl?rev=266926
partial interface Document {
  readonly attribute UndoManager undoManager;
};
