// https://chromium.googlesource.com/chromium/src/+/9848564877f0057f4dcbc98bce061dfa17a9202c
partial interface AudioListener {
  attribute float dopplerFactor;
  attribute float speedOfSound;
};

partial interface BiquadFilterNode {
  const unsigned short LOWPASS = 0;
  const unsigned short HIGHPASS = 1;
  const unsigned short BANDPASS = 2;
  const unsigned short LOWSHELF = 3;
  const unsigned short HIGHSHELF = 4;
  const unsigned short PEAKING = 5;
  const unsigned short NOTCH = 6;
  const unsigned short ALLPASS = 7;
};

partial interface MediaStreamTrackAudioSourceNode {
  readonly attribute any mediaStreamTrack;
};

partial interface PannerNode {
  const unsigned short EQUALPOWER = 0;
  const unsigned short HRTF = 1;
  const unsigned short SOUNDFIELD = 2;
  const unsigned short LINEAR_DISTANCE = 0;
  const unsigned short INVERSE_DISTANCE = 1;
  const unsigned short EXPONENTIAL_DISTANCE = 2;

  // https://chromium.googlesource.com/chromium/src/+/9848564877f0057f4dcbc98bce061dfa17a9202c
  undefined setVelocity(float x, float y, float z);
};
