partial interface RTCCertificate {
  any getSupportedAlgorithms();
};

partial interface RTCDataChannel {
  readonly attribute boolean reliable;
  readonly attribute short stream;
};

[Exposed=Window]
interface RTCIdentityErrorEvent : Event {
  readonly attribute DOMString idp;
  readonly attribute DOMString loginUrl;
  readonly attribute DOMString protocol;
};

[Exposed=Window]
interface RTCIdentityEvent : Event {
  readonly attribute DOMString assertion;
};

partial interface RTCPeerConnection {
  readonly attribute any defaultIceServers;
  any getDefaultIceServers();

  sequence<MediaStream> getLocalStreams();
  sequence<MediaStream> getRemoteStreams();
  undefined addStream(MediaStream stream, optional any mediaConstraints);
  undefined removeStream(MediaStream stream);
  MediaStream getStreamById(DOMString id);

  RTCDTMFSender createDTMFSender(MediaStreamTrack track);

  attribute EventHandler onaddstream;
  attribute EventHandler onremovestream;
  attribute EventHandler onidentityresult;
  attribute EventHandler onidpassertionerror;
  attribute EventHandler onidpvalidationerror;
  attribute EventHandler onpeeridentity;
};

partial interface RTCPeerConnectionIceErrorEvent {
  readonly attribute any hostCandidate;
};

partial interface RTCRtpReceiver {
  // https://henbos.github.io/webrtc-timing/#rtcrtpreceiver-interface
  attribute double? playoutDelayHint;

  readonly attribute RTCDtlsTransport rtcpTransport;
};

partial interface RTCRtpSender {
  readonly attribute RTCDtlsTransport rtcpTransport;
};

partial interface RTCRtpTransceiver {
  readonly attribute boolean stopped;
};

// https://github.com/mozilla/gecko-dev/blob/dd042f25a8da58d565d199dcfebe4f34db64863c/dom/webidl/WebrtcDeprecated.webidl
[Exposed=Window]
interface mozRTCIceCandidate : RTCIceCandidate {
  constructor();
};

[Exposed=Window]
interface mozRTCPeerConnection : RTCPeerConnection {
  constructor();
};

[Exposed=Window]
interface mozRTCSessionDescription : RTCSessionDescription {
  constructor();
};

// https://chromium.googlesource.com/chromium/src/+/6ad4130faeeead16d8bf620c4387283da143ac09/third_party/blink/renderer/modules/peerconnection/rtc_peer_connection.idl#68
[Exposed=Window]
interface webkitRTCPeerConnection {
  constructor();
};
