partial interface RTCCertificate {
  any getSupportedAlgorithms();
};

partial interface RTCDataChannel {
  readonly attribute boolean reliable;
  readonly attribute short stream;
};

interface RTCIdentityErrorEvent : Event {
  readonly attribute DOMString idp;
  readonly attribute DOMString loginUrl;
  readonly attribute DOMString protocol;
};

interface RTCIdentityEvent : Event {
  readonly attribute DOMString assertion;
};

partial interface RTCPeerConnection {
  readonly attribute any defaultIceServers;
  any getDefaultIceServers();

  sequence<MediaStream> getLocalStreams();
  sequence<MediaStream> getRemoteStreams();
  undefined addStream(MediaStream stream, optional any mediaConstraints);
  undefined removeStream(MediaStream stream);
  MediaStream getStreamById(DOMString id);

  RTCDTMFSender createDTMFSender(MediaStreamTrack track);

  attribute EventHandler onaddstream;
  attribute EventHandler onremovestream;
  attribute EventHandler onidentityresult;
  attribute EventHandler onidpassertionerror;
  attribute EventHandler onidpvalidationerror;
  attribute EventHandler onpeeridentity;
};

partial interface RTCPeerConnectionIceErrorEvent {
  readonly attribute any hostCandidate;
};

partial interface RTCRtpReceiver {
  readonly attribute RTCDtlsTransport rtcpTransport;
};

partial interface RTCRtpSender {
  readonly attribute RTCDtlsTransport rtcpTransport;
};

partial interface RTCRtpTransceiver {
  readonly attribute boolean stopped;
};

[Exposed=Window]
interface webkitRTCPeerConnection {
  constructor();
};
